begin;

alter table public.operational_backups
  add column storage_path text,
  add column root_sha256 text check (root_sha256 is null or root_sha256 ~ '^[0-9a-f]{64}$'),
  add column row_count bigint not null default 0 check (row_count >= 0),
  add column byte_count bigint not null default 0 check (byte_count >= 0),
  add column completed_at timestamptz;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values (
  'vendify-operational-backups',
  'vendify-operational-backups',
  false,
  52428800,
  array['application/gzip','application/json','application/x-ndjson']
)
on conflict (id) do update set
  public=false,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

-- No storage.objects policy is intentional. Authenticated browser sessions cannot
-- enumerate, upload or download these objects. A server-side worker uses service_role;
-- downloads are issued as short-lived signed URLs after the owner check.

comment on column public.operational_backups.storage_path is
  'Private Storage path of the v2 manifest. Never exposed as a public URL.';
comment on table public.operational_backup_parts is
  'Immutable checksummed chunks generated by a server-side worker; direct browser access is revoked.';

commit;
